service: nodejs
frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  stage: dev
  region: eu-west-1
  runtime: nodejs18.x

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  getUser:
    handler: lib/user/controller.getUser
    events:
      - httpApi:
          path: /{email}
          method: get
  registerUser:
    handler: lib/user/register-user/controller.register
    events:
      - httpApi:
          path: /register
          method: post
  loginUser:
    handler: lib/user/login/controller.login
    events:
      - httpApi:
          path: /login
          method: post
